# Train models from Final score data

### ** check env and deps

In [1]:
print("Hello World!")

Hello World!

In [ ]:
# Which env??

# import sys
# print(sys.executable)

# download deps through terminal
# .\sklearn-env\Scripts\python.exe -m pip install numpy pandas matplotlib seaborn scikit-learn

In [4]:
# download deps through notebook
# import sys
# !{sys.executable} -m pip install numpy pandas matplotlib seaborn scikit-learn

## 1- Imports

In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import(
    mean_absolute_error,
    mean_squared_error,
    )
sns.set_style("whitegrid") # to make the plots look nicer

## 2- Upload the dataset

In [16]:
df = pd.read_csv("data/student_performance_finalscore.csv")

## 3- EDA

In [17]:
df.head()

,Student_ID,Age,Gender,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Tutoring_Sessions_Per_Week,Family_Income_Level,Exam_Anxiety_Score,Final_Score
0,STU00001,17,Female,8.20,80.0,7.3,2.3,3.2,3.07,No,Online,Average,Average,Yes,3,High,1.8,87.10
1,STU00002,22,Male,4.07,69.2,7.9,3.6,0.5,2.66,Yes,Offline,Average,Good,No,2,Middle,1.0,92.03
2,STU00003,23,Female,5.07,74.2,6.7,2.6,4.7,3.27,No,Hybrid,Average,Good,No,1,Middle,4.2,95.37
3,STU00004,22,Female,5.82,82.5,3.7,3.3,2.3,2.87,No,Offline,Average,Excellent,No,0,Middle,3.6,90.73
4,STU00005,21,Male,3.42,90.8,7.4,7.0,3.1,2.82,Yes,Offline,Average,Good,No,2,Middle,4.5,74.71

In [ ]:
print(df.shape)
# found: shape is (1000, 8) which means 1000 rows and 8 columns

(8000, 18)

In [ ]:
print(df.info())
# found: no null values, all columns are either int64 or object
# found: the variable (y) is Final_Score, which is a numerical column 
# found: numerical columns(x) are: Age, Hours_Studied, Attendance, Sleep_Hours, Stress_Level, Screen_Time, Previous_GPA, Tutoring_Sessions_Per_Week, Exam_Anxiety_Score
# found: categorical columns(x) are: Gender, Part_Time_Job, Study_Method, Diet_Quality, Internet_Quality, Extracurricular, Family_Income_Level

<class 'pandas.DataFrame'>
RangeIndex: 8000 entries, 0 to 7999
Data columns (total 18 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Student_ID                  8000 non-null   str
 1   Age                         8000 non-null   int64
 2   Gender                      8000 non-null   str
 3   Hours_Studied               8000 non-null   float64
 4   Attendance                  8000 non-null   float64
 5   Sleep_Hours                 8000 non-null   float64
 6   Stress_Level                8000 non-null   float64
 7   Screen_Time                 8000 non-null   float64
 8   Previous_GPA                8000 non-null   float64
 9   Part_Time_Job               8000 non-null   str
 10  Study_Method                8000 non-null   str
 11  Diet_Quality                8000 non-null   str
 12  Internet_Quality            8000 non-null   str
 13  Extracurricular             8000 non-null   str
 14  Tutoring_Sessions_Per_Week  8000 non-null   int64
 15  Family_Income_Level         8000 non-null   str
 16  Exam_Anxiety_Score          8000 non-null   float64
 17  Final_Score                 8000 non-null   float64
dtypes: float64(8), int64(2), str(8)
memory usage: 1.1 MB
None

In [ ]:
print(df.isnull().sum())
# found: no null values

Student_ID                    0
Age                           0
Gender                        0
Hours_Studied                 0
Attendance                    0
Sleep_Hours                   0
Stress_Level                  0
Screen_Time                   0
Previous_GPA                  0
Part_Time_Job                 0
Study_Method                  0
Diet_Quality                  0
Internet_Quality              0
Extracurricular               0
Tutoring_Sessions_Per_Week    0
Family_Income_Level           0
Exam_Anxiety_Score            0
Final_Score                   0
dtype: int64

In [ ]:
print(df.duplicated().sum())
# found: no duplicated rows

0

In [ ]:
print(df.describe())
# found: the final score is between 0 and 100

               Age  Hours_Studied   Attendance  Sleep_Hours  Stress_Level  \
count  8000.000000    8000.000000  8000.000000  8000.000000   8000.000000
mean     20.494375       4.983845    79.933375     6.989125      5.014175
std       2.285962       1.951715     9.656594     1.192898      1.940126
min      17.000000       0.020000    43.300000     3.000000      1.000000
25%      18.000000       3.680000    73.400000     6.200000      3.700000
50%      20.500000       4.980000    80.100000     7.000000      5.000000
75%      22.000000       6.312500    86.600000     7.800000      6.300000
max      24.000000      12.000000   100.000000    10.000000     10.000000

       Screen_Time  Previous_GPA  Tutoring_Sessions_Per_Week  \
count  8000.000000   8000.000000                 8000.000000
mean      4.024525      2.992408                    1.700625
std       1.481908      0.489530                    1.112836
min       0.500000      1.500000                    0.000000
25%       3.000000      2.670000                    1.000000
50%       4.000000      2.990000                    2.000000
75%       5.000000      3.330000                    2.000000
max       9.600000      6.700000                    5.000000

       Exam_Anxiety_Score  Final_Score
count         8000.000000  8000.000000
mean             4.494238    83.205649
std              1.685571    12.756728
min              1.000000    22.810000
25%              3.300000    75.507500
50%              4.400000    86.510000
75%              5.600000    93.080000
max             10.000000    99.980000

## 4- x , y

In [25]:
x = df.drop(
    columns=["Student_ID", "Final_Score"]
)
x

,Age,Gender,Hours_Studied,Attendance,Sleep_Hours,Stress_Level,Screen_Time,Previous_GPA,Part_Time_Job,Study_Method,Diet_Quality,Internet_Quality,Extracurricular,Tutoring_Sessions_Per_Week,Family_Income_Level,Exam_Anxiety_Score
0,17,Female,8.20,80.0,7.3,2.3,3.2,3.07,No,Online,Average,Average,Yes,3,High,1.8
1,22,Male,4.07,69.2,7.9,3.6,0.5,2.66,Yes,Offline,Average,Good,No,2,Middle,1.0
2,23,Female,5.07,74.2,6.7,2.6,4.7,3.27,No,Hybrid,Average,Good,No,1,Middle,4.2
3,22,Female,5.82,82.5,3.7,3.3,2.3,2.87,No,Offline,Average,Excellent,No,0,Middle,3.6
4,21,Male,3.42,90.8,7.4,7.0,3.1,2.82,Yes,Offline,Average,Good,No,2,Middle,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,18,Female,6.45,93.6,9.7,5.4,5.9,3.28,No,Online,Poor,Excellent,Yes,3,Middle,3.8
7996,20,Non-Binary,0.80,94.4,7.6,6.7,2.2,3.73,Yes,Offline,Poor,Good,Yes,2,Middle,4.5
7997,19,Female,3.76,96.4,6.8,6.9,3.1,1.81,No,Hybrid,Poor,Good,No,0,Low,2.2
7998,20,Female,3.87,79.2,8.2,8.2,4.9,3.36,No,Hybrid,Good,Excellent,Yes,2,Low,3.1
7999,23,Female,6.87,74.5,4.9,2.0,2.4,2.48,Yes,Offline,Good,Good,Yes,3,Middle,3.0

In [ ]:
# Target - Label
y = df["Final_Score"]
y

0       87.10
1       92.03
2       95.37
3       90.73
4       74.71
        ...
7995    98.58
7996    72.58
7997    63.95
7998    85.19
7999    97.50
Name: Final_Score, Length: 8000, dtype: float64

## 5- Train, Validate, Test (Train Split)

- 8000 students:
    - 80% 6400 -> Development
        - 56% 4480 TRAIN
        - 24% 1920 VALIDATION

- 20% 1600 -> Final TEST

### Sum
- (56% Train)
- (24% Validation)
- (20% Test)

In [28]:
# first split to hide the test data
x_train_full, x_test, y_train_full, y_test = train_test_split(
    x,
        y,
        test_size=0.2,
        random_state=40
)

# second split from the rest of the whole data
x_train, x_val, y_train, y_val = train_test_split(
    x_train_full,
    y_train_full,
    test_size=0.3,
    random_state=36
)

# 6- Data Types handling

In [29]:
# 1- Numerical values
numeric_features = x.select_dtypes(
    include=["int64", "float64"]
).columns

print(numeric_features)

Index(['Age', 'Hours_Studied', 'Attendance', 'Sleep_Hours', 'Stress_Level',
       'Screen_Time', 'Previous_GPA', 'Tutoring_Sessions_Per_Week',
       'Exam_Anxiety_Score'],
      dtype='str')

In [30]:
# 2- Categorical values
categorical_features = x.select_dtypes(
    include=["object", "string"]
).columns

print(categorical_features)

Index(['Gender', 'Part_Time_Job', 'Study_Method', 'Diet_Quality',
       'Internet_Quality', 'Extracurricular', 'Family_Income_Level'],
      dtype='str')

## 7- Preprocessing Linear Regression

#### Since we can't use the categorical feature as they are with the linear Model should we use 
### ** OneHotEncoder **

In [31]:
# 2 processes
linear_preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler,
            numeric_features
        ),
        (
            "cat",
            OneHotEncoder(
                handle_unknown="ignore"
            ),
            categorical_features
        )
    ]
)

## 8- First Model
### - Linear Regression pipeline since we have contiuose values